development:
  clients:
    default:
      uri: "mongodb+srv://jpcast:pro123@proytrack.la0ps9g.mongodb.net/proytrack_development?retryWrites=true&w=majority&authSource=admin"
      options:
        ssl: true
        retry_writes: true
        server_selection_timeout: 5



  options:
test:
  clients:
    default:
      uri: "mongodb+srv://jpcast:pro123@proytrack.la0ps9g.mongodb.net/proytrack_development?retryWrites=true&w=majority&authSource=admin"
      options:
        ssl: true
        retry_writes: true
        server_selection_timeout: 5
production:
  clients:
    default:
      uri: "mongodb+srv://jpcast:pro123@proytrack.la0ps9g.mongodb.net/proytrack_development?retryWrites=true&w=majority&authSource=admin"
      options:
        ssl: true
        retry_writes: true
        server_selection_timeout: 5        
