name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 178.156.195.249 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_rsa deploy@178.156.195.249 "echo ✅ Conexión exitosa"

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa deploy@178.156.195.249 << 'EOF'
            set -e

            # Configurar rbenv
            export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
            eval "$(rbenv init -)"

            cd /home/deploy/proytrack || exit 1

            echo "=== Pulling latest code ==="
            git fetch origin main
            git reset --hard origin/main

            echo "=== Installing gems ==="
            bundle install --deployment --without development test

            echo "=== Migrating DB ==="
            RAILS_ENV=production rails db:migrate

            echo "=== Precompiling assets ==="
            RAILS_ENV=production rails assets:precompile

            echo "=== Restarting services ==="
            sudo systemctl restart puma
            sudo systemctl restart nginx

            echo "✅ Deploy finished!"
          EOF
