name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 178.156.195.249 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 deploy@178.156.195.249 << 'EOF'
            cd /home/deploy/proytrack || exit 1
            git pull origin main
            bundle install --deployment --without development test
            RAILS_ENV=production rails db:migrate
            RAILS_ENV=production rails assets:precompile
            sudo systemctl restart puma
            sudo systemctl restart nginx
          EOF
